api:
  url: https://love-calculator.p.mashape.com/getPercentage?fname=%s&sname=%s
  header: X-Mashape-Key
  key: aKhRBkgi2xmshSdmi9NEjXJZAcu1p1xWdt7jsn813kxMJ5uxAh

db:
  url: jdbc:postgresql://localhost:5432/lovecalculator
  user: love
  pwd: love